
default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci if ENV['CI']
    match(app_identifier: "burhanrashid52.whattodo", type: "appstore", readonly: true, api_key_path: "fastlane/store.json")
    updated_version_number = bump_build_number()
    increment_build_number(build_number: updated_version_number)
    increment_version_number(version_number: ENV["REACT_NATIVE_BUILD_NAME"])
    build_app(workspace: "YourApp.xcworkspace", scheme: "YourAppScheme") # Replace with your actual workspace and scheme
    pilot(api_key_path: "fastlane/store.json", skip_waiting_for_build_processing: true)
  end

  lane :generate_certificates do
    match(type: "appstore", readonly: false)
  end

  def bump_build_number()
    latest_build_number = latest_testflight_build_number(initial_build_number: 0, api_key_path: "fastlane/store.json")
    return (latest_build_number + 1)
  end
end